# Generated by Django 3.2.18 on 2023-04-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, max_length=10)),
                ('imageUrl', models.CharField(max_length=255)),
                ('category', models.ManyToManyField(blank=True, related_name='category_products', to='core.Category')),
            ],
        ),
    ]
